import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
# file_path =r"C:\Users\Lenovo\Desktop\Employee_Project\employee_salary_analysis.csv" 
df=pd.read_csv("employee_salary_analysis.csv")
print(df.head(10))
print("*************************************")
print(df.tail(10))
print("*************************************")
df.info()
print("*************************************")
print(df.describe())
print("*************************************")
print("Dataset Shape:",df.shape)
print("Dataset Columns:",df.columns)
print("Data Type:",df.dtypes)
print("************************************")
print(df['Name'])
print("************************************")
print(df[['Name','Department','Total_Salary']])
print("**************************************")
print(df[30:61])
print("************************************")
print(df[df['Total_Salary']>25000])
print("************************************")
print(df[df['Experience_Years']>8])
print("************************************")
print(df[df['Department']=='AI'])
print("*************************************")
print(df[df['Gender']=='Female'])
print("*************************************")
print(df[df['Performance_Rating']>4.5])
print("*************************************")
print(df[(df['Overtime_Hours']>=10)&(df['Overtime_Hours']<=25)])
print("*************************************")
print(df[(df['Experience_Years']>5)&(df["Performance_Rating"]>4.0)])
print("*************************************")
df['Tax']=df['Total_Salary']*0.10
print(df[['Name','Total_Salary','Tax']].head())
print("*************************************")
salary_array=np.array(df["Total_Salary"])
print("Maximum Salary:",np.max(salary_array))
print("Minimum Salary:",np.min(salary_array))
print("Mean Salary:",np.mean(salary_array))
print("Sum of Salaries:",np.sum(salary_array))
print("*************************************")
print(df.groupby('Department')['Total_Salary'].mean())
print("*************************************")
print(df.groupby('Gender')['Performance_Rating'].mean())
print("*************************************")
print(df.groupby('Department')['Salary'].max())
print("*************************************")
print(df.groupby('Department')['Experience_Years'].min())
print("*************************************")
print(df.groupby('Department')['Employee_ID'].count())
print("*************************************")
df.groupby('Department')['Total_Salary'].mean().plot(kind='bar',color='skyblue')
plt.title('Average Total salary by Department')
plt.xlabel('Department')
plt.ylabel('Average Salary')
plt.show()
print("*************************************")
plt.hist(df['Total_Salary'],bins=15,color='blue',edgecolor='black')
plt.title('Distribution of Total Salary')
plt.xlabel('Total Salary')
plt.ylabel('Frequency')
plt.show()
print("*************************************")
plt.plot(df['Employee_ID'].head(20),df['Total_Salary'].head(20),marker='o',color='pink')
plt.title('Employee ID vs Total Salary (First 20)')
plt.xlabel('Employee ID')
plt.ylabel('Total Salary')
plt.show()
print("*************************************")
sns.scatterplot(data=df,x='Experience_Years',y='Total_Salary',hue='Department')
plt.title('Experiance Years vs Total Salary')
plt.show()
print("*************************************")
sns.barplot(data=df,x='Department',y='Salary')
plt.title('Average Salary per Department')
plt.show()
print("*************************************")
sns.histplot(data=df,x='Total_Salary',kde=True,color='purple')
plt.title('Salary Histogram with KDE')
plt.savefig('employee_salary_histogram.png',dpi=300)
plt.show()